---
ENVIRONMENT: dev
VPC_NAME: Jenkins-VPC
REGION: us-west-2
CLUSTER_NAME: UtopiaClusterWC
SECRET_NAME: prod/Walter/secrets
DB_HOST: db_host
SECRET_KEY: secret_key
DB_USER: db_user
DB_PASSWORD: db_password
AWS_ACCOUNT_ID: 026390315914