apiVersion: v1
kind: ConfigMap
metadata:
  name: utopia-config
data:
  CONFIRMATION_CODE_LENGTH: "50"
  STRIPE_ID_LENGTH: "25"
  ADMIN_ROLE_ID: "1"
  AGENT_ROLE_ID: "2"
  TRAVELER_ROLE_ID: "3"
  GUEST: "guest"
  ADMIN_REQUIRED: "Must be an admin to access this resource"
  AGENT_REQUIRED: "Must be an admin or agent to access this resource"
  NO_AUTH_RESPONSE: "No credentials provided"
  UNAUTHORIZED: "403"
  NO_AUTH: "401"
  USERS_PORT: "80"
  FLIGHTS_PORT: "80"
  BOOKINGS_PORT: "80"


