version: '3.4'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - backend
    ports:
      - "${MYSQL_PORT_FORWARD}:${MYSQL_DEFAULT}"
  users-api:
    image: "${USER_IMAGE}"
    depends_on:
       - db
    env_file:
      - .env
    environment:
      - DB_HOST=/run/secrets/DB_HOST
      - SECRET_KEY=/run/secrets/SECRET_KEY
      - DB_USER=/run/secrets/DB_USER
      - DB_USER_PASSWORD=/run/secrets/DB_USER_PASSWORD
      - DB=/run/secrets/DB
    secrets:
      - DB_HOST
      - SECRET_KEY
      - DB_USER
      - DB_USER_PASSWORD
      - DB
    container_name: users-api
    restart: always
    networks:
      - backend
    ports:
      - "${USERS_PORT}:${USERS_PORT}"
  bookings-api:
    image: "${BOOKING_IMAGE}"
    depends_on:
       - db
    env_file:
      - .env
    environment:
      - DB_HOST=/run/secrets/DB_HOST
      - SECRET_KEY=/run/secrets/SECRET_KEY
      - DB_USER=/run/secrets/DB_USER
      - DB_USER_PASSWORD=/run/secrets/DB_USER_PASSWORD
      - DB=/run/secrets/DB
    secrets:
      - DB_HOST
      - SECRET_KEY
      - DB_USER
      - DB_USER_PASSWORD
      - DB
    container_name: bookings-api
    restart: always
    networks:
      - backend
    ports:
      - "${BOOKINGS_PORT}:${BOOKINGS_PORT}"
  flights-api:
    image: "${FLIGHT_IMAGE}"
    depends_on:
       - db
    env_file:
      - .env
    environment:
      - DB_HOST=/run/secrets/DB_HOST
      - SECRET_KEY=/run/secrets/SECRET_KEY
      - DB_USER=/run/secrets/DB_USER
      - DB_USER_PASSWORD=/run/secrets/DB_USER_PASSWORD
      - DB=/run/secrets/DB
    secrets:
      - DB_HOST
      - SECRET_KEY
      - DB_USER
      - DB_USER_PASSWORD
      - DB
    container_name: flights-api
    restart: always
    networks:
      - backend
    ports:
      - "${FLIGHTS_PORT}:${FLIGHTS_PORT}"
networks:
  backend:

secrets:
    DB_HOST:
      file: ./docker-compose_local/db_host
    SECRET_KEY:
      file: ./docker-compose_local/secret_key
    DB_USER:
      file: ./docker-compose_local/db_user
    DB_USER_PASSWORD:
      file: ./docker-compose_local/db_user_password
    DB:
      file: ./docker-compose_local/db