version: '3'
services:
  USERS: 
    environment: 
     - HOST_DOMAIN=https://users-api 
    image: "123124124.dkr.ecr.us-west-2.amazonaws.com/USERS:latest"
    ports:
      - ":"
    logging:
      driver: awslogs
      options:
        awslogs-group: ecs_wc
        awslogs-region: 
        awslogs-stream-prefix: USERS
